### ISSUE TITLE
`iatlasGraphQLClient::query_heritability_results(datasets = "TCGA")` returning fewer results in staging api

### ISSUE THREAD

**Issue by heimannch** [CRI-iAtlas/iatlasGraphQLClient#17]
Production API/db:
```
> heritability <- iatlasGraphQLClient::query_heritability_results(datasets = "TCGA")
> dim(heritability)
[1] 996  11
```

Staging API/db:
```
> heritability <- iatlasGraphQLClient::query_heritability_results(datasets = "TCGA")
> dim(heritability)
[1] 76 11
```

**Comment by andrewelamb** [comment]
@heimannch I don't know this data very well, currently their is one source file being used to populate the database with 76 results:

**Comment by andrewelamb** [comment]
When I added them previously not all features where in the database, but tht seems to have been resolved.

**Comment by heimannch** [comment]
Looking perfect now, thanks!

**Comment by heimannch** [comment]
I still get fewer results when I load the app with the staging database, maybe it'll take a while to propagate changes?

**Comment by andrewelamb** [comment]
@heimannch I still need to rebuild the database, this should be ready later today
